# Generated by Django 5.2.1 on 2025-07-11 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_medicalreport_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='uploaded_at',
        ),
    ]
