# Generated by Django 5.2.1 on 2025-07-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_medicalreport_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='supabase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
