# Generated by Django 5.2.1 on 2025-07-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_medicalreport_supabase_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='original_file',
            field=models.URLField(max_length=500),
        ),
    ]
