# Generated by Django 5.2.1 on 2025-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_medicalreport_original_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='medicalreport',
            name='supabase_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
