# Generated by Django 5.2.1 on 2025-07-11 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicalreport_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 11, 15, 8, 2, 293649, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
